FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN mvn -B -DskipTests clean package

FROM eclipse-temurin:21-jre AS runtime
WORKDIR /app
COPY --from=build /build/target/*-SNAPSHOT.jar /app/app.jar
RUN set -eux \
  && groupadd -r appgroup || true \
  && useradd -r -g appgroup -s /usr/sbin/nologin appuser || true \
  && chown -R appuser:appgroup /app
USER appuser
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]
